/* FAQ Daten – Bauleitung Tiefbau Netzbau (cablex / Swisscom)
   Sprachen: DE / FR / IT
   Kategorien: safety | tech | docs
   Inhalte: Orientierungshilfe, ersetzen keine geltenden Normen oder Weisungen.
*/

window.I18N = {
  de: {
    skip: "Zum Inhalt springen",
    eyebrow: "Bauleitung Tiefbau · Netzbau",
    heroTitle: "Fragen & Antworten für Bauleiter",
    heroLead: "Praxiswissen zu Sicherheit, Technik und Dokumentation im Tiefbau für den Netzbau. Orientiert an SUVA, VSS und SIA.",
    catAll: "Alle",
    catSafety: "Sicherheit & Arbeitsschutz",
    catTech: "Tiefbau-Technik & Material",
    catDocs: "Doku, Abnahme & Qualität",
    empty: "Keine Einträge in dieser Kategorie.",
    footerText: "Diese Seite dient als interne Wissensbasis für Bauleiter im Tiefbau Netzbau. Inhalte sind Orientierungshilfe und ersetzen keine geltenden Normen oder Weisungen.",
    footerRefs: "Referenzen:",
    htmlLang: "de"
  },
  fr: {
    skip: "Aller au contenu",
    eyebrow: "Direction des travaux · Génie civil · Réseau",
    heroTitle: "Questions & réponses pour les chefs de chantier",
    heroLead: "Connaissances pratiques sur la sécurité, la technique et la documentation dans le génie civil pour la construction de réseaux. Selon SUVA, VSS et SIA.",
    catAll: "Tout",
    catSafety: "Sécurité & santé au travail",
    catTech: "Technique & matériaux",
    catDocs: "Documentation, réception & qualité",
    empty: "Aucune entrée dans cette catégorie.",
    footerText: "Ce site sert de base de connaissances interne pour les chefs de chantier en génie civil dans la construction de réseaux. Les contenus sont indicatifs et ne remplacent pas les normes ou directives en vigueur.",
    footerRefs: "Références :",
    htmlLang: "fr"
  },
  it: {
    skip: "Vai al contenuto",
    eyebrow: "Direzione lavori · Genio civile · Rete",
    heroTitle: "Domande e risposte per i capicantiere",
    heroLead: "Conoscenze pratiche su sicurezza, tecnica e documentazione nel genio civile per la costruzione di reti. In linea con SUVA, VSS e SIA.",
    catAll: "Tutto",
    catSafety: "Sicurezza & salute sul lavoro",
    catTech: "Tecnica & materiali",
    catDocs: "Documentazione, collaudo & qualità",
    empty: "Nessuna voce in questa categoria.",
    footerText: "Questo sito è una base di conoscenza interna per i capicantiere nel genio civile per la costruzione di reti. I contenuti sono indicativi e non sostituiscono norme o direttive in vigore.",
    footerRefs: "Riferimenti:",
    htmlLang: "it"
  }
};

window.FAQ_DATA = {
  de: [
    // ===== Sicherheit & Arbeitsschutz =====
    { cat: "safety", q: "Ab welcher Grabentiefe ist ein Verbau erforderlich?",
      a: "Gemäss SUVA-Richtlinie ist ein Grabenverbau ab einer Tiefe von <strong>1.50 m</strong> grundsätzlich erforderlich. Bei nicht standfestem Boden oder dynamischen Belastungen (Verkehr, Maschinen) kann ein Verbau bereits früher nötig sein. Alternativ ist eine ausreichende Böschung gemäss Bodenklasse möglich." },
    { cat: "safety", q: "Welche persönliche Schutzausrüstung (PSA) ist auf der Baustelle Pflicht?",
      a: "Helm, Sicherheitsschuhe Klasse S3, Warnkleidung mindestens Klasse 2 sowie Arbeitshandschuhe sind Standard. Je nach Tätigkeit kommen Schutzbrille, Gehörschutz, Staubmaske (FFP-Klasse je nach Material) und Schnittschutz hinzu. Die PSA muss CE-zertifiziert und in einwandfreiem Zustand sein." },
    { cat: "safety", q: "Wie sichere ich offene Gräben gegen Absturz?",
      a: "Ab <strong>2.0 m Tiefe</strong> ist eine Absturzsicherung Pflicht: Geländer mit Hand-, Knie- und Bordleiste, Abdeckungen oder Auffangsysteme. Über Nacht müssen Gräben in öffentlichen Bereichen vollständig abgedeckt oder mit blinkenden Leuchten signalisiert sein." },
    { cat: "safety", q: "Welche Schutzabstände gelten bei Hochspannungsleitungen?",
      a: "Ohne Schutzmassnahmen gelten Sicherheitsabstände von <strong>3 m</strong> bis 220 kV bzw. <strong>5 m</strong> bis 380 kV (BUSt-Vorgaben). Vor Arbeiten in der Nähe sind Werkleitungsbetreiber zwingend einzubeziehen und gegebenenfalls Freischaltung, Erdung oder Schutzgerüste zu organisieren." },
    { cat: "safety", q: "Welche Signalisation ist bei Arbeiten an befahrenen Strassen vorgeschrieben?",
      a: "Die Signalisation richtet sich nach der <strong>VSS 40 886</strong> bzw. SN 640 886. Pro Geschwindigkeitsbereich gelten Vorwarnungen, Geschwindigkeitsreduktionen und Spurführungen. Das Signalisationskonzept ist mit der Polizei und/oder Werkhof abzusprechen und durch geschultes Personal aufzustellen." },
    { cat: "safety", q: "Wann muss eine Baustellenabsperrung erfolgen?",
      a: "Im öffentlichen Bereich grundsätzlich immer: stabile Schutzgitter, Bauzaun oder Leitwände. Im Innerortsbereich nachts beleuchtet, mit Reflektoren und gut sichtbaren Zugangssperren. Fluchtwege für Anwohner und Rettungsdienste sind freizuhalten." },
    { cat: "safety", q: "Was tun bei Verdacht auf Altlasten oder kontaminiertes Erdreich?",
      a: "Arbeiten sofort einstellen, Bauleitung und Bauherrschaft informieren. Eine Probe durch eine akkreditierte Stelle prüfen lassen und Aushubmaterial getrennt zwischenlagern. Erst nach Vorliegen einer Materialdeklaration und behördlicher Freigabe darf weitergearbeitet werden." },
    { cat: "safety", q: "Wie ist der Rettungsweg im Graben zu organisieren?",
      a: "Pro <strong>15 m</strong> Grabenlänge ist ein Auf- und Abstieg (Leiter) erforderlich, der mindestens 1.0 m über das Geländeniveau ragt. Die Leitern müssen rutschfest stehen und freigehalten werden. Bei Verbau sind passende Durchstiege oder Treppentürme vorzusehen." },
    { cat: "safety", q: "Welche Schulungen sind für Tiefbau-Personal erforderlich?",
      a: "Mindestens ein Sicherheitsverantwortlicher mit SUVA-Anerkennung pro Baustelle, sowie Schulungen zu Erste Hilfe, Verbau, Signalisation, Maschinenführerausweis (z. B. Bagger, Walze) und Werkleitungssensibilisierung. Nachweise sind auf der Baustelle bereitzuhalten." },
    { cat: "safety", q: "Wie erkenne ich unbekannte Werkleitungen im Aushub?",
      a: "Vor Aushubbeginn sind die Werkleitungspläne aller Werke (Strom, Wasser, Gas, Telekom) einzuholen. Im sensiblen Bereich nur per Saugbagger oder von Hand öffnen. Bei unerwartetem Auffinden Arbeiten stoppen, sichern und Werkbetreiber kontaktieren." },
    { cat: "safety", q: "Was ist bei der Handhabung schwerer Lasten zu beachten?",
      a: "Ab <strong>25 kg</strong> (Männer) bzw. 15 kg (Frauen) sind technische Hilfsmittel zu prüfen. Anschlagmittel müssen geprüft und gekennzeichnet sein (jährliche Prüfung). Lastaufnahme nur durch ausgebildete Anschläger, Hebebereich absperren." },
    { cat: "safety", q: "Welche Lärm- und Vibrationsgrenzwerte sind einzuhalten?",
      a: "Tagsüber gelten im Wohngebiet typischerweise 60-65 dB(A), nachts 45-50 dB(A) – kommunale Vorgaben sind verbindlich. Ab 85 dB(A) ist Gehörschutz Pflicht. Erschütterungen werden nach SN 640 312a beurteilt; bei sensiblen Bauten ist eine Erschütterungsmessung sinnvoll." },
    { cat: "safety", q: "Wann ist ein Sicherheits- und Gesundheitsschutzplan (SiGePlan) Pflicht?",
      a: "Sobald mehrere Unternehmen gleichzeitig oder nacheinander auf der Baustelle tätig sind oder besondere Gefahren bestehen (z. B. Grabenarbeiten > 1.5 m). Der Plan wird von der Bauleitung erstellt, auf der Baustelle ausgehängt und laufend nachgeführt." },
    { cat: "safety", q: "Was ist beim Notfall- oder Unfallablauf zu tun?",
      a: "Sichern – Alarmieren – Erste Hilfe leisten. Notrufnummern (144 / 117 / 118 / 145) sind auf der Baustelle anzuschlagen. Jeder Unfall wird im Bautagebuch und beim SUVA-Fall an die Versicherung gemeldet; bei schweren Unfällen ist die Unfallstelle nicht zu verändern." },

    // ===== Tiefbau-Technik & Material =====
    { cat: "tech", q: "Welche Grabenprofile sind im Netzbau üblich?",
      a: "Standardprofile sind Schlitzgräben (B 0.3-0.5 m) für Microducts und Normgräben (B 0.6-1.0 m) für mehrere Rohrebenen. Bei tiefen Trassen mit gemeinsamer Belegung kommen Sammelgräben (B 1.2-1.5 m) zum Einsatz. Profile sind in den Ausführungsplänen verbindlich festgelegt." },
    { cat: "tech", q: "Welche Mindestüberdeckung gilt für Glasfaserkabel?",
      a: "Im Trottoir <strong>60 cm</strong>, unter der Fahrbahn <strong>80 cm</strong> Überdeckung sind die Regelwerte gemäss VSS. Unter besonderen Bedingungen (Fels, Bestand) kann mit Schutzrohren und mechanischem Schutz reduziert werden – immer mit Zustimmung der Bauherrschaft." },
    { cat: "tech", q: "Welche Mindestüberdeckung gilt für Niederspannungskabel?",
      a: "Niederspannung typischerweise <strong>70-80 cm</strong>, Mittelspannung mindestens <strong>100 cm</strong> unter Fahrbahn. Bei Kreuzungen mit anderen Werken sind die werkspezifischen Vorgaben (z. B. Swissgrid, VSE) und die VSS-Norm SN 592 000 zu beachten." },
    { cat: "tech", q: "Welche Bettungsmaterialien sind zugelassen?",
      a: "Für die Kabel-/Rohrbettung ist <strong>Sand 0/8</strong> oder gewaschener Kies 0/16 üblich, frei von scharfkantigen Bestandteilen. Schichtdicke unter und über dem Rohr je nach Vorgabe 10-15 cm. Recyclingmaterial nur wenn ausdrücklich zugelassen." },
    { cat: "tech", q: "Wie wird ein Kabelschutzrohr fachgerecht verlegt?",
      a: "Rohre auf tragfähiger Bettung verlegen, Stossverbindungen mit Muffen schliessen und gegen Eindringen von Material schützen. Vor dem Verfüllen Zugdraht einziehen, Lagepläne aktualisieren. Bögen mit zulässigem Mindestradius (typ. 12× Rohrdurchmesser) ausführen." },
    { cat: "tech", q: "Welche Rohrdurchmesser sind für FTTH-Microducts üblich?",
      a: "Standard sind Microducts <strong>7/3.5 mm</strong>, <strong>10/6 mm</strong>, <strong>12/8 mm</strong> und <strong>16/12 mm</strong>. Im Speedpipe-Verband werden 7er- oder 12er-Bündel verlegt. Die Wahl richtet sich nach Kabelquerschnitt, Einblaslänge und Bestandsinfrastruktur." },
    { cat: "tech", q: "Wann ist Spülbohrverfahren (HDD) sinnvoll?",
      a: "Bei Querungen von Strassen, Gewässern oder Bahnen ohne offenen Aushub. Voraussetzungen sind ausreichende Überdeckung, bekannte Werkleitungssituation und geeigneter Baugrund (kein grobes Geröll, kein Fels ohne Spezialausrüstung). Vorerkundung und Bewilligung beim Werkträger sind zwingend." },
    { cat: "tech", q: "Welche Anforderungen gelten an das Verfüllmaterial?",
      a: "Verfüllmaterial muss den Vorgaben der <strong>VSS SN 640 585b</strong> entsprechen. Üblich sind Kiessand-Gemische 0/45 oder 0/32, schichtweise verdichtet. Wiederverwendung des Aushubs nur, wenn die Eignung nachgewiesen ist (Sieblinie, Plastizität, Wassergehalt)." },
    { cat: "tech", q: "Wie wird die Verdichtung lagenweise korrekt ausgeführt?",
      a: "Schichten von <strong>20-30 cm</strong>, jede Schicht verdichtet (Stampfer, Vibrationsplatte). Verdichtungsgrad gem. Vorgabe (typ. <strong>ME ≥ 80 MN/m²</strong> im Strassenbau, höher im Belag-Unterbau). Prüfung mittels Lastplattenversuch oder Plattendruckversuch dokumentieren." },
    { cat: "tech", q: "Welche Schachtgrössen sind im Netzbau Standard?",
      a: "Telekom-Standardschächte sind <strong>K1 (60×80 cm)</strong>, <strong>K2 (90×135 cm)</strong> und <strong>K3 (120×180 cm)</strong>. Die Wahl richtet sich nach Spleissaufkommen, Kabelmenge und Manövrierraum. Deckel müssen verkehrslastgerecht (Klasse D400 im Strassenbereich) ausgeführt sein." },
    { cat: "tech", q: "Wie werden Trassen mehrerer Werke gemeinsam verlegt?",
      a: "In einem Sammelgraben mit definierter Belegung: Strom unten, Telekom darüber, dazwischen separierende Sandschichten oder Trennvliese. Lagepläne und Höhenangaben sind verbindlich. Werkträger-Abstandsregeln (z. B. 20 cm horizontal, 30 cm vertikal zwischen Strom und FO) sind einzuhalten." },
    { cat: "tech", q: "Welche Mindestabstände gelten zwischen Glasfaser- und Stromtrasse?",
      a: "Üblicherweise <strong>20 cm horizontal</strong> und <strong>30 cm vertikal</strong> zur Niederspannung. Bei Mittelspannung sind grössere Abstände oder mechanischer Schutz (Stahlplatten, Halbschalen) gefordert. Massgebend sind die VSE- und Swisscom-Vorgaben sowie die Werkanweisung." },
    { cat: "tech", q: "Wie wird Microtrenching ausgeführt und wann ist es zulässig?",
      a: "Schmaler Schnitt (1.5-3 cm breit, 30-50 cm tief) mit Spezialfräse, Verlegung der Microducts und Verguss mit Spezialmörtel. Zulässig nur in genehmigten Belagsstrecken, ohne kreuzende Werkleitungen im Bereich und nach Absprache mit der Strassenverwaltung." },
    { cat: "tech", q: "Welche Warn- und Markierungsbänder müssen eingelegt werden?",
      a: "Über jeder Trasse ein farbcodiertes Warnband ca. 30 cm über der Rohrebene: <strong>grün/weiss</strong> für Telekom, <strong>rot</strong> für Strom, <strong>blau</strong> für Wasser, <strong>gelb</strong> für Gas. Im Strassenoberbau wird zusätzlich eine Trassenwarnfolie (Detektionsband) eingelegt." },

    // ===== Doku, Abnahme & Qualität =====
    { cat: "docs", q: "Welche Pläne müssen vor Baubeginn vorliegen?",
      a: "Ausführungspläne, Werkleitungspläne aller Werke, Signalisationskonzept, SiGePlan, Aushubdeklaration sowie Bewilligungen (Grabungsbewilligung, Strassenbenützung). Ohne vollständige Unterlagen darf nicht mit dem Aushub begonnen werden." },
    { cat: "docs", q: "Wie dokumentiere ich die ausgeführten Arbeiten?",
      a: "Im Bautagebuch täglich: Wetter, Personal, Maschinen, ausgeführte Arbeiten, Vorkommnisse. Zusätzlich Aufmasse, Pläne mit Rotstift-Eintrag (Revisionsplan), Fotos und Lieferscheine. Die Dokumentation ist Grundlage für Abrechnung und Abnahme." },
    { cat: "docs", q: "Welche Fotodokumentation ist Pflicht?",
      a: "Vor Baubeginn (Bestandsaufnahme), während des Aushubs (Werkleitungen, Bettung, Verfüllung schichtweise) und nach Abschluss (Wiederherstellung). Fotos müssen Datum, Ort und idealerweise GPS-Koordinaten enthalten. Pro Schacht und kritischer Stelle mindestens 4 Aufnahmen." },
    { cat: "docs", q: "Wie wird Aufmass und Mengennachweis erstellt?",
      a: "Aufmass laufend mit dem Polier, festgehalten in Aufmassblättern oder digital (Tablet/App). Mengen nach Leistungsverzeichnis (NPK) ermittelt, mit Plänen und Fotos belegt. Strittige Positionen vor Verfüllung gemeinsam einmessen und unterzeichnen lassen." },
    { cat: "docs", q: "Welche Werkleitungspläne sind nach Bauende zu aktualisieren?",
      a: "Sämtliche neuen oder veränderten Werkleitungen sind ins GIS einzumessen (Lage und Höhe) und im Werkleitungsplan nachzuführen. Tolerierte Genauigkeit: <strong>±10 cm horizontal, ±5 cm vertikal</strong> bei aktiver Einmessung vor Verfüllung. Übergabe an den Werkträger digital (z. B. DXF, GeoIV)." },
    { cat: "docs", q: "Welche Toleranzen gelten bei der Einmessung?",
      a: "Lage horizontal typischerweise <strong>±10 cm</strong>, Höhe <strong>±5 cm</strong> bei offener Einmessung. Bei Spülbohrungen sind Toleranzen grösser; sie sind im Vertrag bzw. Pflichtenheft geregelt. Vermessung erfolgt georeferenziert (LV95)." },
    { cat: "docs", q: "Welche Rolle hat die Bauleitung gegenüber Auftraggeber und Werkträger?",
      a: "Die Bauleitung vertritt den Auftraggeber auf der Baustelle: Koordination, Qualitätsüberwachung, Abnahmen, Termin- und Kostenkontrolle. Sie ist Ansprechpartner für Behörden, Werkträger und Unternehmen. Anweisungen sind schriftlich zu erteilen (Bautagebuch, Pendenzenliste)." },
    { cat: "docs", q: "Was beinhaltet eine Bauabnahme?",
      a: "Gemeinsame Begehung mit Auftraggeber, Bauleitung und Unternehmer. Geprüft werden Vollständigkeit, Qualität, Dokumentation und Funktion (z. B. OTDR-Messung Glasfaser). Festgestellte Mängel werden im Abnahmeprotokoll mit Fristen festgehalten." },
    { cat: "docs", q: "Wie lange laufen Garantiefristen im Tiefbau?",
      a: "Nach SIA 118 beträgt die Rügefrist <strong>2 Jahre</strong> für offene Mängel, die Verjährungsfrist <strong>5 Jahre</strong> für verdeckte Mängel ab Abnahme. Für Belagsarbeiten gelten oft separate Garantien (z. B. 2 Jahre auf den Belag, 5 Jahre auf die Trasse)." },
    { cat: "docs", q: "Welche Mängel werden im Protokoll festgehalten?",
      a: "Alle sichtbaren Abweichungen von Plan, Leistungsbeschrieb oder anerkannten Regeln der Technik. Pro Mangel: Beschreibung, Ort, Foto, verantwortliche Firma und Frist zur Behebung. Verdeckte Mängel werden bei Entdeckung nachgemeldet." },
    { cat: "docs", q: "Wie werden Nachträge und Mehrleistungen abgerechnet?",
      a: "Vor Ausführung mit dem Auftraggeber schriftlich vereinbaren (Nachtragsofferte). Mengen und Preise nach NPK-Positionen oder Regie (mit Rapport). Ohne genehmigten Nachtrag ist die Vergütung gefährdet – darum: <strong>Erst genehmigen lassen, dann ausführen</strong>." },
    { cat: "docs", q: "Welche Dokumente sind nach Projektabschluss zu archivieren?",
      a: "Werkvertrag, Pläne (As-built), Bautagebuch, Aufmasse, Abnahmeprotokoll, Messprotokolle (OTDR, Verdichtung), Fotodokumentation, Bewilligungen und Lieferscheine. Aufbewahrungsfrist mindestens <strong>10 Jahre</strong>; für Werkleitungspläne dauerhaft." },

    // ===== Ergänzung: Handbuch unterirdischer Netzbau (Swisscom, 2024) =====
    { cat: "safety", q: "Wie wird eine gas- und wasserdichte Kabeleinführung in Gebäuden ausgeführt?",
      a: "Dichtungselemente müssen einem Innen- oder Aussendruck von <strong>0.5 bar</strong> standhalten. In das Mauerwerk werden Stahlrohre einbetoniert, in welche die Kunststoffrohre eingeführt und mit Schrumpfschlauch abgedichtet werden. In Kabelkellern sind alle Durchführungen passiv abzudichten; Vollrohre erhalten eine Brandabschottung mit Abdichtungskissen." },
    { cat: "safety", q: "Wie werden runde Schachtabdeckungen gegen unbefugtes Öffnen gesichert?",
      a: "Mit einer <strong>Absperrplatte</strong> für ø 600 mm Einstiege und einem <strong>SEA-Vorhängeschloss</strong>. Bei Vollgussdeckeln und neueren Rahmen sind die Löcher bereits vorhanden, ältere Rahmen müssen nachgebohrt werden. Bei Guss-Betondeckeln werden die Löcher in den Schachthals gebohrt." },
    { cat: "safety", q: "Werden beim Trassebau Erdbänder mit verlegt?",
      a: "Grundsätzlich <strong>nein</strong>. Massgebend sind die Swisscom-Richtlinien zu Erdungen an Kabelanlagen sowie die Vorgaben für das Kupfernetz und die Erläuterungen von Electrosuisse für den Schwachstrom-Netzbau. Erdungsmassnahmen erfolgen separat gemäss diesen Richtlinien." },
    { cat: "tech", q: "Welche Schachttypen verwendet Swisscom im Netzbau?",
      a: "Vier Haupttypen: <strong>ES</strong> (Einstiegschacht, 3.00×1.50 m, Spleissschacht in Strassen), <strong>KES</strong> (Kleineinstiegschacht, ab 1.00×1.00 m, Neubaustandard), <strong>PS</strong> (Plattenschacht, vor allem im Kulturland) und <strong>KS</strong> (Kontrollschacht, Brunnenring 60/80 cm). KES ist heute der bevorzugte Typ; ES nur noch wo der Platzbedarf für Muffen und Kabel es erfordert." },
    { cat: "tech", q: "Wann wird ein Einstiegschacht (ES) statt eines KES eingesetzt?",
      a: "ES nur als <strong>Ausnahme</strong>, wenn die Platzverhältnisse für Muffen und Kabel den KES überschreiten. Im Neubau ist immer der kleinere Schacht zu bevorzugen. Bestehende Plattenschächte unter Belag werden im Umbau meist auf KES vergrössert." },
    { cat: "tech", q: "Wo werden Plattenschächte (PS) heute noch eingesetzt?",
      a: "Im <strong>Kulturland</strong> und auf schwach befahrenen Strassen bleibt der Plattenschacht die wirtschaftlichste Lösung. Standardabmessungen: 1.00×1.00 m oder 2.05×1.00 m mit Betonplatten 120×27 cm. Im überbauten Bereich werden Plattenschächte im Sanierungsfall auf KES vergrössert." },
    { cat: "tech", q: "Welche wirtschaftlichen Schachtabstände gelten im Anschlussnetz?",
      a: "Richtwerte gemäss Swisscom-Handbuch: <strong>Cu-Teilnehmerkabel</strong> ca. 200-250 m in Bauzone, ca. 500 m ausserhalb; <strong>Glasfaser</strong> ca. 1'000 m in Bauzone, 1'000-6'000 m ausserhalb. Detailerschliessung Schacht-Überführungspunkt bis ca. 200 m. Mindestrohrradien: K100 ≥ 3 m, K55 ≥ 1 m." },
    { cat: "tech", q: "Was unterscheidet Basis- von Detailerschliessung?",
      a: "<strong>Basiserschliessung</strong>: Rohrverbindungen zwischen begehbaren Schächten (ES, KES, PS) sowie zu Zentralen und Verteilern. <strong>Detailerschliessung</strong>: Rohrverbindungen zwischen begehbaren Schächten und Überführungspunkten bzw. Netztrennstellen (Hausanschlüsse). Beide werden separat dimensioniert." },
    { cat: "tech", q: "Aus welchen Schichten besteht ein normierter Strassenaufbau?",
      a: "Von oben: <strong>Oberbau (B)</strong> mit Deckschicht (B4), Bindeschicht (B3), Tragschicht (B2), Fundationsschicht (B1) und Übergangsschicht (B0/Geotextil); <strong>Unterbau (A)</strong> mit verbessertem Untergrund (A3), Damm (A2) und Untergrund (A1). Massgebend sind die VSS-Normen." },
    { cat: "tech", q: "Welche Schachtentwässerung ist bei Spleissschächten zulässig?",
      a: "Zwei Möglichkeiten gemäss Swisscom-Normplänen: <strong>Pumpensumpf</strong> oder <strong>Sickerschacht</strong>. Entwässerungsleitungen und Entlüftungen sind im Normalfall nicht zu bauen. Bei passgenauen Schachtabdeckungen (Gatic, Ermatic) sind die Herstelleranweisungen einzuhalten." },
    { cat: "tech", q: "Wie wird die Verdichtung um Schächte mit Betonsockel kontrolliert?",
      a: "Mit einem <strong>Plattendruckversuch (ME-Messung)</strong> nach SN 670317b bzw. VSS-70317: stufenweises Be- und Entlasten einer starren Platte ø 30 cm und Messung der Setzungen. Werden die ME-Werte nicht erreicht, trägt die ausführende Unternehmung die Kosten. Mangelhafte Verdichtung führt sonst zum sichtbaren Durchstanzen des Betonkranzes." },
    { cat: "docs", q: "Welche Normen sind im unterirdischen Netzbau massgebend?",
      a: "<strong>SIA 205</strong> (Verlegung von Leitungen im Untergrund), <strong>SIA 118</strong> (Allgemeine Vertragsbedingungen), <strong>SIA 405</strong> (Geodaten zu Werkleitungen), die <strong>VSS-Normen</strong> für Strassen- und Tiefbau sowie die <strong>VSE-Vorgaben</strong> für Elektrizitätsanlagen. Zusätzlich gilt die Leitungsverordnung Art. 62 für die Lagedokumentation." },
    { cat: "docs", q: "Welche Objekte sind für PTA einzumessen?",
      a: "Alle Objekte mit Lageattribut in der Netzdokumentation: <strong>Netzkanten</strong> (Erdstrecken = Linie), <strong>Netzknoten</strong> (Schächte, Abzweigungen = Punkt) und <strong>Sonderbauwerke</strong> (z. B. grosse Einstiegsschächte = Polygon). Zusätzlich die Trasselänge zwischen den Netzknoten. PTA = Planning and Design Tool Access." },
    { cat: "docs", q: "Welche Genauigkeit ist beim Einmass gefordert?",
      a: "Gemäss <strong>Leitungsverordnung Art. 62</strong> ist eine Lagegenauigkeit von <strong>±20 cm</strong> einzuhalten. Diese Genauigkeit wird in der Regel nur durch Einmass am offenen Graben erreicht. Die eingesetzte Technologie (GNSS, Tachymeter) muss für Swisscom nachvollziehbar dokumentiert sein." },
    { cat: "docs", q: "In welchem Format wird das digitale Einmass an Swisscom übergeben?",
      a: "Format <strong>1× DXF</strong> mit Struktur <strong>SIA Geo405</strong>. Erfassung in der Regel im Feld mit GNSS oder Tachymeter. Netzkanten und Netzknoten müssen topologisch zusammenhängend sein – Kanten zum gleichen Knoten treffen sich in einem gemeinsamen Punkt." },
    { cat: "docs", q: "Was ist ein Bogenschnitt beim Handeinmass?",
      a: "Eine geodätische Methode zur Punktbestimmung: vom zu erfassenden Punkt werden die Distanzen zu <strong>zwei koordinativ gegebenen Punkten</strong> A und B gemessen. Der neue Punkt ergibt sich als Schnittpunkt der zwei Kreise um A und B mit den gemessenen Distanzen als Radien. Die beiden Masse möglichst rechtwinklig wählen und im Einmassplan eintragen." },
    { cat: "docs", q: "Wie funktioniert das orthogonale Einmass (Rechtwinkelmass)?",
      a: "Mit einem <strong>Winkelprisma</strong> wird der zu erfassende Punkt im rechten Winkel auf eine bestehende Linie (Ordinate) abgebildet und der Abstand gemessen. Die Methode ist einfach in der Anwendung und im Einmassplan einzutragen." },
    { cat: "docs", q: "Wie ist die Kostenbeteiligung bei Strassen- und Werkleitungssanierungen geregelt?",
      a: "Drei Standardfälle: <strong>Strassenneubau</strong> – Werkträger leistet Beitrag für die eigene Trasse; <strong>Strassen- oder Belagssanierung</strong> – meist anteilig nach Nutzfläche; <strong>Werkleitungssanierung</strong> mit gleichzeitigem Anlass – Mitnutzungsbeiträge nach Vereinbarung. Bei Behinderungen durch bestehende Swisscom-Leitungen ist der Aufwand separat zu vereinbaren." }
  ],

  fr: [
    // ===== Sécurité =====
    { cat: "safety", q: "À partir de quelle profondeur un blindage de fouille est-il requis ?",
      a: "Selon la directive SUVA, un blindage est en principe requis dès une profondeur de <strong>1.50 m</strong>. En cas de sol instable ou de charges dynamiques (trafic, machines), il peut être nécessaire plus tôt. Alternativement, un talutage suffisant selon la classe de sol est admis." },
    { cat: "safety", q: "Quel équipement de protection individuelle (EPI) est obligatoire ?",
      a: "Casque, chaussures de sécurité classe S3, vêtements à haute visibilité au moins classe 2 et gants de travail sont la base. Selon l'activité s'ajoutent lunettes, protection auditive, masque (FFP selon le matériau) et protection anti-coupure. L'EPI doit être certifié CE et en parfait état." },
    { cat: "safety", q: "Comment sécuriser une fouille ouverte contre les chutes ?",
      a: "Dès <strong>2.0 m de profondeur</strong>, une protection antichute est obligatoire : garde-corps avec main courante, lisse intermédiaire et plinthe, ou recouvrements. La nuit en zone publique, la fouille doit être entièrement recouverte ou signalée par balises lumineuses." },
    { cat: "safety", q: "Quelles distances de sécurité avec les lignes haute tension ?",
      a: "Sans mesures de protection, les distances minimales sont de <strong>3 m</strong> jusqu'à 220 kV et <strong>5 m</strong> jusqu'à 380 kV. Avant tout travail à proximité, l'exploitant doit être impliqué et, le cas échéant, la mise hors tension, la mise à la terre ou des protections doivent être organisées." },
    { cat: "safety", q: "Quelle signalisation pour des travaux en bord de route ?",
      a: "La signalisation suit la norme <strong>VSS 40 886</strong> (SN 640 886). Selon la vitesse, des présignalisations, réductions de vitesse et guidages sont nécessaires. Le plan de signalisation se valide avec la police ou la voirie, et n'est mis en place que par du personnel formé." },
    { cat: "safety", q: "Quand faut-il une clôture de chantier ?",
      a: "En zone publique, toujours : grilles stables, palissades ou barrières. En localité de nuit, éclairées, avec réflecteurs et accès clairement bloqués. Les voies d'évacuation pour riverains et services de secours doivent rester libres." },
    { cat: "safety", q: "Que faire en cas de soupçon de sols pollués ?",
      a: "Arrêter immédiatement les travaux, informer la direction des travaux et le maître d'ouvrage. Faire analyser un échantillon par un laboratoire accrédité et stocker les déblais à part. Les travaux ne reprennent qu'après déclaration des matériaux et autorisation des autorités." },
    { cat: "safety", q: "Comment organiser les voies d'évacuation dans la fouille ?",
      a: "Tous les <strong>15 m</strong>, une échelle d'accès qui dépasse d'au moins 1.0 m le niveau du terrain. Les échelles doivent être stables et dégagées. En présence de blindage, prévoir des passages ou tours d'escalier adaptés." },
    { cat: "safety", q: "Quelles formations sont nécessaires pour le personnel ?",
      a: "Au moins un responsable sécurité reconnu SUVA par chantier, plus des formations en premiers secours, blindage, signalisation, conduite d'engins (pelle, rouleau) et sensibilisation aux réseaux. Les attestations sont disponibles sur le chantier." },
    { cat: "safety", q: "Comment détecter les réseaux inconnus lors de la fouille ?",
      a: "Avant l'ouverture, demander les plans de tous les exploitants (électricité, eau, gaz, télécom). Dans les zones sensibles, ouvrir par aspiratrice ou à la main. En cas de découverte imprévue, arrêter, sécuriser et contacter l'exploitant." },
    { cat: "safety", q: "Quelles règles pour la manutention de charges lourdes ?",
      a: "Dès <strong>25 kg</strong> (hommes) ou 15 kg (femmes), envisager une aide technique. Les accessoires de levage doivent être contrôlés et marqués (contrôle annuel). Le levage est réservé à des élingueurs formés ; la zone est balisée." },
    { cat: "safety", q: "Quels seuils de bruit et de vibrations respecter ?",
      a: "En zone d'habitation, typiquement 60-65 dB(A) le jour et 45-50 dB(A) la nuit (les exigences communales priment). Dès 85 dB(A), protection auditive obligatoire. Les vibrations sont évaluées selon SN 640 312a ; pour les bâtiments sensibles, des mesures sont recommandées." },
    { cat: "safety", q: "Quand un plan de sécurité et de santé (PSS) est-il obligatoire ?",
      a: "Dès que plusieurs entreprises interviennent simultanément ou successivement, ou en présence de risques particuliers (fouilles > 1.5 m). Il est établi par la direction des travaux, affiché sur le chantier et tenu à jour." },
    { cat: "safety", q: "Que faire en cas d'accident sur le chantier ?",
      a: "Sécuriser – alerter – donner les premiers secours. Les numéros d'urgence (144 / 117 / 118 / 145) sont affichés sur le chantier. Chaque accident est consigné dans le journal et annoncé à l'assurance ; en cas d'accident grave, ne pas modifier les lieux." },

    // ===== Technique & matériaux =====
    { cat: "tech", q: "Quels profils de fouille sont utilisés dans la construction de réseaux ?",
      a: "Profils standards : tranchées étroites (L 0.3-0.5 m) pour microducts et tranchées normales (L 0.6-1.0 m) pour plusieurs niveaux de tubes. En cas de cohabitation, des tranchées collectrices (L 1.2-1.5 m) sont utilisées. Les profils sont définis dans les plans d'exécution." },
    { cat: "tech", q: "Quelle profondeur de recouvrement pour la fibre optique ?",
      a: "Sur trottoir <strong>60 cm</strong>, sous chaussée <strong>80 cm</strong> sont les valeurs de référence selon VSS. En conditions particulières (roche, existant), réduction possible avec tubes de protection et protection mécanique – toujours avec accord du maître d'ouvrage." },
    { cat: "tech", q: "Quelle profondeur pour les câbles basse tension ?",
      a: "Basse tension typiquement <strong>70-80 cm</strong>, moyenne tension au moins <strong>100 cm</strong> sous chaussée. Aux croisements, les prescriptions des exploitants (Swissgrid, AES) et la SN 592 000 s'appliquent." },
    { cat: "tech", q: "Quels matériaux de lit sont admis ?",
      a: "Pour le lit des câbles ou tubes : <strong>sable 0/8</strong> ou gravier lavé 0/16, exempts d'éléments coupants. Épaisseur sous et sur le tube en général 10-15 cm. Matériaux recyclés uniquement si expressément autorisés." },
    { cat: "tech", q: "Comment poser un tube de protection correctement ?",
      a: "Poser sur un lit porteur, raccorder les éléments avec manchons étanches. Avant remblayage, tirer un fil-pilote et mettre à jour les plans. Les courbes respectent le rayon minimal (typ. 12× le diamètre)." },
    { cat: "tech", q: "Quels diamètres pour les microducts FTTH ?",
      a: "Standards : microducts <strong>7/3.5 mm</strong>, <strong>10/6 mm</strong>, <strong>12/8 mm</strong> et <strong>16/12 mm</strong>. En réseau Speedpipe, faisceaux de 7 ou 12. Le choix dépend du câble, de la longueur de soufflage et de l'infrastructure existante." },
    { cat: "tech", q: "Quand utiliser le forage dirigé (HDD) ?",
      a: "Pour des traversées de routes, cours d'eau ou voies sans tranchée ouverte. Conditions : recouvrement suffisant, plan des réseaux connu, sol adapté (pas de blocs grossiers ni roche sans matériel spécial). Une reconnaissance préalable et l'accord de l'exploitant sont indispensables." },
    { cat: "tech", q: "Quelles exigences pour le matériau de remblai ?",
      a: "Conforme à <strong>VSS SN 640 585b</strong>. Mélanges grave 0/45 ou 0/32 fréquents, compactés par couches. Réemploi des déblais uniquement si l'aptitude est démontrée (granulométrie, plasticité, teneur en eau)." },
    { cat: "tech", q: "Comment compacter par couches correctement ?",
      a: "Couches de <strong>20-30 cm</strong>, chaque couche compactée (dameuse, plaque vibrante). Degré selon prescription (typ. <strong>ME ≥ 80 MN/m²</strong>, plus élevé sous chaussée). Essais à la plaque ou plaque dynamique à documenter." },
    { cat: "tech", q: "Quelles tailles de chambres standard ?",
      a: "Chambres télécom standards : <strong>K1 (60×80 cm)</strong>, <strong>K2 (90×135 cm)</strong> et <strong>K3 (120×180 cm)</strong>. Choix selon volume d'épissures, câbles et accès. Tampons résistants aux charges (classe D400 en chaussée)." },
    { cat: "tech", q: "Comment réaliser une tranchée commune avec plusieurs exploitants ?",
      a: "Tranchée collectrice avec affectation définie : électricité en bas, télécom dessus, séparation par sable ou géotextile. Plans et altitudes contraignants. Distances exigées par exploitant (par ex. 20 cm horizontal, 30 cm vertical entre électricité et fibre) à respecter." },
    { cat: "tech", q: "Quelles distances minimales entre fibre et électricité ?",
      a: "En général <strong>20 cm horizontal</strong> et <strong>30 cm vertical</strong> avec la basse tension. En moyenne tension, distances ou protections mécaniques (plaques, demi-coquilles) supérieures. Les prescriptions AES et Swisscom font foi." },
    { cat: "tech", q: "Quand et comment utiliser le microtrenching ?",
      a: "Coupe étroite (1.5-3 cm de largeur, 30-50 cm de profondeur) avec fraise spécialisée, pose des microducts puis scellement au mortier. Admis uniquement sur revêtements autorisés, sans réseaux croisés et après accord avec la voirie." },
    { cat: "tech", q: "Quelles bandes d'avertissement faut-il poser ?",
      a: "Au-dessus de chaque tracé, une bande colorée environ 30 cm au-dessus des tubes : <strong>vert/blanc</strong> télécom, <strong>rouge</strong> électricité, <strong>bleu</strong> eau, <strong>jaune</strong> gaz. Dans la chaussée, un grillage avertisseur détectable est ajouté." },

    // ===== Documentation & qualité =====
    { cat: "docs", q: "Quels plans doivent être disponibles avant le début des travaux ?",
      a: "Plans d'exécution, plans des réseaux, concept de signalisation, PSS, déclaration des déblais et autorisations (fouille, usage routier). Sans dossier complet, l'ouverture ne doit pas commencer." },
    { cat: "docs", q: "Comment documenter les travaux réalisés ?",
      a: "Journal de chantier quotidien : météo, personnel, machines, travaux, événements. En complément : métrés, plans avec annotations (révision), photos et bons de livraison. Cette documentation est la base du décompte et de la réception." },
    { cat: "docs", q: "Quelle documentation photo est obligatoire ?",
      a: "Avant les travaux (état initial), pendant les travaux (réseaux, lit, remblayage par couches) et après (remise en état). Les photos doivent comporter date, lieu et idéalement coordonnées GPS. Au moins 4 prises par chambre ou point critique." },
    { cat: "docs", q: "Comment établir métrés et justificatifs de quantités ?",
      a: "Métrés réalisés en continu avec le chef d'équipe, consignés sur fiches ou en numérique. Quantités selon CAN (catalogue des articles normalisés), justifiées par plans et photos. Les positions litigieuses sont mesurées et signées avant remblayage." },
    { cat: "docs", q: "Quels plans de réseaux sont à mettre à jour après les travaux ?",
      a: "Tous les nouveaux réseaux ou modifications sont relevés au SIG (planimétrie et altimétrie) et reportés au plan. Précision attendue : <strong>±10 cm horizontal, ±5 cm vertical</strong> en relevé avant remblayage. Remise à l'exploitant en numérique (DXF, conformément OGéo)." },
    { cat: "docs", q: "Quelles tolérances pour le relevé ?",
      a: "Position horizontale typiquement <strong>±10 cm</strong>, altitude <strong>±5 cm</strong> en relevé à ciel ouvert. Pour les forages dirigés, les tolérances sont plus larges et fixées au contrat. Le géoréférencement est en MN95." },
    { cat: "docs", q: "Quel est le rôle de la direction des travaux envers maître d'ouvrage et exploitants ?",
      a: "Elle représente le maître d'ouvrage : coordination, contrôle qualité, réceptions, suivi des délais et coûts. C'est l'interlocuteur des autorités, exploitants et entreprises. Les instructions sont données par écrit (journal, liste de points en suspens)." },
    { cat: "docs", q: "Que comprend une réception des travaux ?",
      a: "Visite commune avec maître d'ouvrage, direction des travaux et entreprise. Vérification de l'intégralité, qualité, documentation et fonction (par ex. mesure OTDR fibre). Les défauts constatés sont consignés au procès-verbal avec délais." },
    { cat: "docs", q: "Quelles durées de garantie dans le génie civil ?",
      a: "Selon SIA 118 : délai d'avis de défauts <strong>2 ans</strong> pour défauts apparents, prescription <strong>5 ans</strong> pour défauts cachés à compter de la réception. Pour les revêtements, garanties souvent séparées (par ex. 2 ans sur le revêtement, 5 ans sur le tracé)." },
    { cat: "docs", q: "Quels défauts consigner au procès-verbal ?",
      a: "Toutes les divergences visibles par rapport au plan, à la description des prestations ou aux règles de l'art. Pour chaque défaut : description, lieu, photo, entreprise responsable et délai de réparation. Les défauts cachés sont annoncés à leur découverte." },
    { cat: "docs", q: "Comment décompter avenants et prestations supplémentaires ?",
      a: "À convenir par écrit avant exécution avec le maître d'ouvrage (offre d'avenant). Quantités selon positions CAN ou en régie (avec rapport). Sans avenant approuvé, la rémunération est compromise : <strong>faire approuver puis exécuter</strong>." },
    { cat: "docs", q: "Quels documents archiver après le projet ?",
      a: "Contrat, plans (as-built), journal, métrés, procès-verbaux, mesures (OTDR, compactage), photos, autorisations et bons de livraison. Conservation au moins <strong>10 ans</strong> ; pour les plans de réseaux, conservation permanente." },

    // ===== Compléments : Manuel de construction de réseau souterrain (Swisscom, 2024) =====
    { cat: "safety", q: "Comment réaliser une entrée de câbles étanche au gaz et à l'eau ?",
      a: "Les éléments d'étanchéité doivent résister à une pression intérieure ou extérieure de <strong>0.5 bar</strong>. Des tubes en acier sont noyés dans la maçonnerie ; les tubes plastique y sont introduits et étanchés avec une gaine thermorétractable. En cave de câbles, toutes les traversées doivent être étanchées passivement ; les tubes pleins reçoivent un compartimentage coupe-feu avec coussins d'étanchéité." },
    { cat: "safety", q: "Comment sécuriser les tampons ronds contre l'ouverture non autorisée ?",
      a: "Avec une <strong>plaque de blocage</strong> pour les regards ø 600 mm et un <strong>cadenas SEA</strong>. Sur les couvercles en fonte et les cadres récents, les trous sont déjà présents ; sur les anciens cadres ils doivent être percés. Sur les couvercles fonte-béton, les trous sont percés dans le col du regard." },
    { cat: "safety", q: "Pose-t-on des liaisons équipotentielles lors de la construction du tracé ?",
      a: "En principe <strong>non</strong>. Les directives Swisscom sur les mises à la terre des installations de câbles, les prescriptions pour le réseau cuivre et les explications d'Electrosuisse pour le courant faible font foi. Les mises à la terre sont organisées séparément selon ces directives." },
    { cat: "tech", q: "Quels types de chambres Swisscom utilise-t-il ?",
      a: "Quatre types principaux : <strong>ES</strong> (chambre d'accès, 3.00×1.50 m, pour épissures sous chaussée), <strong>KES</strong> (petite chambre d'accès, dès 1.00×1.00 m, standard en construction neuve), <strong>PS</strong> (chambre à dalles, surtout en zone agricole) et <strong>KS</strong> (chambre de contrôle, anneau ø 60/80 cm). Le KES est aujourd'hui le type préféré ; l'ES est réservé aux cas où la place pour manchons et câbles l'exige." },
    { cat: "tech", q: "Quand utilise-t-on un ES plutôt qu'un KES ?",
      a: "L'ES n'est plus qu'une <strong>exception</strong>, lorsque la place pour manchons et câbles dépasse les capacités d'un KES. En construction neuve, on privilégie toujours le plus petit. Les chambres à dalles existantes sous revêtement sont en général converties en KES lors de la rénovation." },
    { cat: "tech", q: "Où utilise-t-on encore les chambres à dalles (PS) ?",
      a: "En <strong>zone agricole</strong> et sur les routes peu fréquentées, la chambre à dalles reste la solution la plus économique. Dimensions standards : 1.00×1.00 m ou 2.05×1.00 m avec dalles béton 120×27 cm. En zone bâtie, les PS sont agrandies en KES lors d'une rénovation." },
    { cat: "tech", q: "Quelles distances économiques entre chambres dans le réseau de raccordement ?",
      a: "Valeurs de référence du manuel Swisscom : <strong>câble cuivre abonné</strong> env. 200-250 m en zone à bâtir, env. 500 m hors zone ; <strong>fibre optique</strong> env. 1'000 m en zone à bâtir, 1'000-6'000 m hors zone. Desserte de détail chambre - point de transition jusqu'à env. 200 m. Rayons minimaux : K100 ≥ 3 m, K55 ≥ 1 m." },
    { cat: "tech", q: "Quelle différence entre desserte de base et de détail ?",
      a: "<strong>Desserte de base</strong> : tubes entre chambres visitables (ES, KES, PS) et vers les centraux et répartiteurs. <strong>Desserte de détail</strong> : tubes entre chambres visitables et points de transition (raccordements clients). Les deux sont dimensionnées séparément." },
    { cat: "tech", q: "Quelles couches composent une structure de chaussée normée ?",
      a: "De haut en bas : <strong>superstructure (B)</strong> avec couche de roulement (B4), couche de liaison (B3), couche de base (B2), couche de fondation (B1) et couche de transition (B0/géotextile) ; <strong>infrastructure (A)</strong> avec sol amélioré (A3), remblai (A2) et terrain naturel (A1). Les normes VSS sont déterminantes." },
    { cat: "tech", q: "Quel système de drainage est admis pour les chambres d'épissure ?",
      a: "Deux possibilités selon les plans normalisés Swisscom : <strong>puisard de pompage</strong> ou <strong>puits perdu</strong>. Conduites de drainage et ventilations ne sont en règle générale pas posées. Avec des tampons à ajustement serré (Gatic, Ermatic), suivre les instructions du fabricant." },
    { cat: "tech", q: "Comment contrôle-t-on le compactage autour des chambres avec socle béton ?",
      a: "Par un <strong>essai à la plaque (mesure ME)</strong> selon SN 670317b ou VSS-70317 : chargement et déchargement par paliers d'une plaque rigide ø 30 cm et mesure du tassement. Si les valeurs ME ne sont pas atteintes, l'entreprise prend les frais à sa charge. Un compactage insuffisant provoque un poinçonnement visible de la couronne béton." },
    { cat: "docs", q: "Quelles normes sont déterminantes pour la construction souterraine ?",
      a: "<strong>SIA 205</strong> (pose des conduites souterraines), <strong>SIA 118</strong> (conditions générales pour les travaux de construction), <strong>SIA 405</strong> (géodonnées des réseaux), les <strong>normes VSS</strong> pour route et génie civil ainsi que les <strong>prescriptions AES</strong> pour les installations électriques. S'y ajoute l'art. 62 de l'ordonnance sur les lignes pour la documentation de position." },
    { cat: "docs", q: "Quels objets doivent être relevés pour PTA ?",
      a: "Tous les objets ayant un attribut de position dans la documentation réseau : <strong>arêtes réseau</strong> (tronçons enterrés = ligne), <strong>nœuds réseau</strong> (chambres, dérivations = point) et <strong>ouvrages spéciaux</strong> (par ex. grandes chambres = polygone). Aussi la longueur du tracé entre les nœuds. PTA = Planning and Design Tool Access." },
    { cat: "docs", q: "Quelle précision exige-t-on lors du relevé ?",
      a: "Selon l'<strong>art. 62 de l'ordonnance sur les lignes</strong>, une précision de position de <strong>±20 cm</strong> est exigée. Cette précision n'est atteinte en règle générale qu'en mesurant à ciel ouvert. La technologie utilisée (GNSS, tachéomètre) doit être documentée de manière traçable pour Swisscom." },
    { cat: "docs", q: "Dans quel format le relevé numérique est-il remis à Swisscom ?",
      a: "Format <strong>1× DXF</strong> avec structure <strong>SIA Geo405</strong>. Acquisition en règle générale sur le terrain avec GNSS ou tachéomètre. Les arêtes et nœuds doivent être topologiquement cohérents – les arêtes vers un même nœud se rejoignent en un point commun." },
    { cat: "docs", q: "Qu'est-ce que la méthode de l'intersection (Bogenschnitt) ?",
      a: "Une méthode géodésique de détermination de point : les distances vers <strong>deux points de coordonnées connues</strong> A et B sont mesurées. Le nouveau point est le point d'intersection des deux cercles de centres A et B et de rayons égaux aux distances mesurées. Choisir les deux distances aussi orthogonales que possible et reporter sur le plan de relevé." },
    { cat: "docs", q: "Comment fonctionne le relevé orthogonal (équerre) ?",
      a: "Avec une <strong>équerre optique (prisme)</strong>, le point à relever est projeté à angle droit sur une ligne existante (ordonnée) et la distance est mesurée. La méthode est simple à mettre en œuvre ; elle est consignée sur le plan de relevé." },
    { cat: "docs", q: "Comment se répartissent les coûts lors d'assainissements de route ou de réseau ?",
      a: "Trois cas standards : <strong>construction routière neuve</strong> – l'exploitant participe pour son propre tracé ; <strong>assainissement de route ou revêtement</strong> – contribution généralement proportionnelle à la surface utilisée ; <strong>assainissement de réseau</strong> simultané – contributions par accord de coutilisation. En cas de gêne par des lignes Swisscom existantes, l'effort est conventionné séparément." }
  ],

  it: [
    // ===== Sicurezza =====
    { cat: "safety", q: "Da quale profondità è necessaria la palancolatura dello scavo?",
      a: "Secondo la direttiva SUVA, una palancolatura è di principio richiesta da una profondità di <strong>1.50 m</strong>. In presenza di terreno instabile o carichi dinamici (traffico, macchine), può essere necessaria già prima. In alternativa è ammessa una scarpata adeguata alla classe di terreno." },
    { cat: "safety", q: "Quale equipaggiamento di protezione individuale (DPI) è obbligatorio?",
      a: "Casco, scarpe di sicurezza classe S3, indumenti ad alta visibilità almeno classe 2 e guanti da lavoro sono lo standard. A seconda dell'attività si aggiungono occhiali, protezione dell'udito, maschera (FFP secondo il materiale) e protezione antitaglio. I DPI devono essere certificati CE e in perfetto stato." },
    { cat: "safety", q: "Come proteggere uno scavo aperto contro le cadute?",
      a: "Da <strong>2.0 m di profondità</strong> è obbligatoria una protezione anticaduta: parapetto con corrente principale, intermedio e tavola fermapiede, oppure copertura. Di notte in zona pubblica, lo scavo va completamente coperto o segnalato con luci lampeggianti." },
    { cat: "safety", q: "Quali distanze di sicurezza dalle linee ad alta tensione?",
      a: "Senza misure di protezione: distanze minime <strong>3 m</strong> fino a 220 kV e <strong>5 m</strong> fino a 380 kV. Prima dei lavori l'esercente va coinvolto e, se necessario, vanno organizzate disinserzione, messa a terra o protezioni." },
    { cat: "safety", q: "Quale segnaletica per lavori su strade transitate?",
      a: "La segnaletica segue la norma <strong>VSS 40 886</strong> (SN 640 886). In funzione della velocità servono preavvisi, riduzioni di velocità e guida della corsia. Il piano di segnaletica va concordato con polizia o ufficio tecnico e posato solo da personale formato." },
    { cat: "safety", q: "Quando è necessaria una recinzione di cantiere?",
      a: "In zona pubblica sempre: griglie stabili, recinzioni o barriere. In località di notte illuminate, con catarifrangenti e accessi chiaramente bloccati. Le vie di fuga per residenti e soccorsi vanno mantenute libere." },
    { cat: "safety", q: "Cosa fare in caso di sospetto di terreno contaminato?",
      a: "Sospendere i lavori, informare direzione lavori e committente. Far analizzare un campione da un laboratorio accreditato e stoccare separatamente il materiale di scavo. Si riprende solo dopo dichiarazione dei materiali e nulla osta delle autorità." },
    { cat: "safety", q: "Come organizzare le vie di fuga nello scavo?",
      a: "Ogni <strong>15 m</strong>, una scala di accesso che sporge almeno 1.0 m sopra il terreno. Le scale devono essere stabili e mantenute libere. In presenza di palancolatura, prevedere passaggi o torri scala adatti." },
    { cat: "safety", q: "Quali formazioni sono richieste per il personale?",
      a: "Almeno un responsabile della sicurezza riconosciuto SUVA per cantiere, oltre a formazioni in primo soccorso, palancolatura, segnaletica, conduzione macchine (escavatore, rullo) e sensibilizzazione alle reti. Gli attestati vanno tenuti in cantiere." },
    { cat: "safety", q: "Come identificare reti sconosciute durante lo scavo?",
      a: "Prima dello scavo richiedere i piani di tutti gli esercenti (elettricità, acqua, gas, telecom). Nelle zone sensibili aprire con aspiratore o a mano. In caso di ritrovamento imprevisto fermarsi, mettere in sicurezza e contattare l'esercente." },
    { cat: "safety", q: "Quali regole per la movimentazione di carichi pesanti?",
      a: "Da <strong>25 kg</strong> (uomini) o 15 kg (donne), valutare un ausilio tecnico. Gli accessori di sollevamento devono essere controllati e marcati (controllo annuale). Sollevamento solo da imbragatori formati; zona di sollevamento delimitata." },
    { cat: "safety", q: "Quali limiti per rumore e vibrazioni?",
      a: "In zona abitativa, tipicamente 60-65 dB(A) di giorno e 45-50 dB(A) di notte (le prescrizioni comunali prevalgono). Da 85 dB(A) la protezione dell'udito è obbligatoria. Le vibrazioni si valutano secondo SN 640 312a; per edifici sensibili sono consigliate misurazioni." },
    { cat: "safety", q: "Quando è obbligatorio un piano di sicurezza e salute (PSS)?",
      a: "Quando più imprese intervengono contemporaneamente o in successione, o in presenza di rischi particolari (scavi > 1.5 m). Viene redatto dalla direzione lavori, esposto in cantiere e aggiornato." },
    { cat: "safety", q: "Cosa fare in caso di infortunio sul cantiere?",
      a: "Mettere in sicurezza – allertare – prestare primo soccorso. I numeri di emergenza (144 / 117 / 118 / 145) sono affissi in cantiere. Ogni infortunio è registrato nel giornale e notificato all'assicurazione; in caso di infortunio grave non modificare il luogo." },

    // ===== Tecnica & materiali =====
    { cat: "tech", q: "Quali profili di scavo si usano nella costruzione di reti?",
      a: "Profili standard: scavi stretti (L 0.3-0.5 m) per microtubi e scavi normali (L 0.6-1.0 m) per più livelli di tubazioni. In caso di coabitazione si usano scavi collettori (L 1.2-1.5 m). I profili sono definiti nei piani di esecuzione." },
    { cat: "tech", q: "Quale copertura minima per la fibra ottica?",
      a: "Su marciapiede <strong>60 cm</strong>, sotto carreggiata <strong>80 cm</strong> sono i valori di riferimento VSS. In condizioni particolari (roccia, esistente) è possibile ridurre con tubi di protezione e protezione meccanica – sempre con accordo della committenza." },
    { cat: "tech", q: "Quale copertura per i cavi di bassa tensione?",
      a: "Bassa tensione di norma <strong>70-80 cm</strong>, media tensione almeno <strong>100 cm</strong> sotto carreggiata. Agli incroci valgono le prescrizioni degli esercenti (Swissgrid, AES) e la SN 592 000." },
    { cat: "tech", q: "Quali materiali per il letto di posa sono ammessi?",
      a: "Per il letto di cavi/tubi: <strong>sabbia 0/8</strong> o ghiaia lavata 0/16, prive di elementi taglienti. Spessore sotto e sopra il tubo in genere 10-15 cm. Materiali riciclati solo se espressamente autorizzati." },
    { cat: "tech", q: "Come posare correttamente un tubo di protezione?",
      a: "Posa su letto portante, giunti chiusi con manicotti a tenuta. Prima del riempimento, inserire un filo guida e aggiornare i piani. Le curve rispettano il raggio minimo (tipico 12× il diametro)." },
    { cat: "tech", q: "Quali diametri per i microtubi FTTH?",
      a: "Standard: microtubi <strong>7/3.5 mm</strong>, <strong>10/6 mm</strong>, <strong>12/8 mm</strong> e <strong>16/12 mm</strong>. In rete Speedpipe, fasci da 7 o 12. La scelta dipende da cavo, lunghezza di soffiaggio e infrastruttura esistente." },
    { cat: "tech", q: "Quando usare la trivellazione orizzontale (HDD)?",
      a: "Per attraversare strade, corsi d'acqua o linee senza scavo aperto. Premesse: copertura sufficiente, situazione reti nota, terreno idoneo (no ciottoli grossi o roccia senza attrezzature speciali). Indagine preliminare e nulla osta dell'esercente sono indispensabili." },
    { cat: "tech", q: "Quali requisiti per il materiale di riempimento?",
      a: "Conforme a <strong>VSS SN 640 585b</strong>. Frequenti miscele ghiaia-sabbia 0/45 o 0/32, compattate per strati. Riutilizzo dello scavo solo se idoneità dimostrata (granulometria, plasticità, contenuto d'acqua)." },
    { cat: "tech", q: "Come compattare correttamente per strati?",
      a: "Strati di <strong>20-30 cm</strong>, ogni strato compattato (pestello, piastra vibrante). Grado secondo prescrizione (tipico <strong>ME ≥ 80 MN/m²</strong>, maggiore sotto pavimentazione). Prove a piastra o piastra dinamica da documentare." },
    { cat: "tech", q: "Quali misure standard per le camerette?",
      a: "Camerette telecom standard: <strong>K1 (60×80 cm)</strong>, <strong>K2 (90×135 cm)</strong> e <strong>K3 (120×180 cm)</strong>. Scelta in funzione di giunzioni, cavi e spazio di manovra. Chiusini resistenti al carico (classe D400 in carreggiata)." },
    { cat: "tech", q: "Come realizzare uno scavo comune con più esercenti?",
      a: "Scavo collettore con assegnazione definita: elettricità in basso, telecom sopra, separazione con strati di sabbia o geotessile. Piani e quote sono vincolanti. Distanze richieste dagli esercenti (es. 20 cm orizzontale, 30 cm verticale tra elettricità e fibra) da rispettare." },
    { cat: "tech", q: "Quali distanze minime tra fibra ed elettricità?",
      a: "In genere <strong>20 cm orizzontale</strong> e <strong>30 cm verticale</strong> rispetto alla bassa tensione. In media tensione distanze o protezioni meccaniche (piastre, semigusci) maggiori. Determinanti sono le prescrizioni AES e Swisscom." },
    { cat: "tech", q: "Quando e come usare il microtrenching?",
      a: "Taglio stretto (larghezza 1.5-3 cm, profondità 30-50 cm) con fresa specializzata, posa dei microtubi e sigillatura con malta. Ammesso solo su pavimentazioni autorizzate, senza reti incrocianti e previo accordo con l'autorità stradale." },
    { cat: "tech", q: "Quali nastri di avvertimento posare?",
      a: "Sopra ogni tracciato, un nastro colorato a circa 30 cm sopra i tubi: <strong>verde/bianco</strong> telecom, <strong>rosso</strong> elettricità, <strong>blu</strong> acqua, <strong>giallo</strong> gas. Nel corpo stradale si aggiunge una rete di avvertimento rilevabile." },

    // ===== Documentazione & qualità =====
    { cat: "docs", q: "Quali piani devono essere disponibili prima dell'inizio dei lavori?",
      a: "Piani di esecuzione, piani delle reti, concetto di segnaletica, PSS, dichiarazione dei materiali di scavo e autorizzazioni (scavo, uso stradale). Senza dossier completo non si deve iniziare lo scavo." },
    { cat: "docs", q: "Come documentare i lavori eseguiti?",
      a: "Giornale di cantiere giornaliero: meteo, personale, macchine, lavori, eventi. In aggiunta: misurazioni, piani con annotazioni (revisione), foto e bolle di consegna. Questa documentazione è la base per consuntivo e collaudo." },
    { cat: "docs", q: "Quale documentazione fotografica è obbligatoria?",
      a: "Prima dei lavori (stato iniziale), durante i lavori (reti, letto di posa, riempimento per strati) e dopo (ripristino). Le foto devono contenere data, luogo e idealmente coordinate GPS. Almeno 4 scatti per cameretta o punto critico." },
    { cat: "docs", q: "Come redigere misurazioni e prova delle quantità?",
      a: "Misurazioni in continuo con il capo squadra, registrate su schede o in digitale. Quantità secondo CPN (catalogo prestazioni normalizzate), giustificate da piani e foto. Le posizioni contestate vanno misurate e firmate prima del riempimento." },
    { cat: "docs", q: "Quali piani di rete aggiornare al termine dei lavori?",
      a: "Tutte le nuove reti o modifiche sono rilevate nel SIT (planimetria e quota) e riportate nei piani. Precisione attesa: <strong>±10 cm orizzontale, ±5 cm verticale</strong> con rilievo prima del riempimento. Consegna all'esercente in digitale (DXF, conforme OGI)." },
    { cat: "docs", q: "Quali tolleranze per il rilievo?",
      a: "Posizione orizzontale tipicamente <strong>±10 cm</strong>, quota <strong>±5 cm</strong> a scavo aperto. Per le trivellazioni le tolleranze sono maggiori e fissate per contratto. Il georiferimento è in CH1903+ / LV95." },
    { cat: "docs", q: "Qual è il ruolo della direzione lavori verso committente ed esercenti?",
      a: "Rappresenta il committente: coordinamento, controllo qualità, collaudi, monitoraggio di tempi e costi. È l'interlocutore per autorità, esercenti e imprese. Le istruzioni vanno date per iscritto (giornale, lista pendenze)." },
    { cat: "docs", q: "Cosa comprende un collaudo?",
      a: "Sopralluogo congiunto con committente, direzione lavori e impresa. Si verificano completezza, qualità, documentazione e funzionalità (es. misura OTDR fibra). I difetti riscontrati sono messi a verbale con termini di risoluzione." },
    { cat: "docs", q: "Quali termini di garanzia nel genio civile?",
      a: "Secondo SIA 118: termine di avviso difetti <strong>2 anni</strong> per difetti visibili, prescrizione <strong>5 anni</strong> per difetti occulti dalla data di collaudo. Per pavimentazioni spesso garanzie separate (es. 2 anni sulla pavimentazione, 5 anni sul tracciato)." },
    { cat: "docs", q: "Quali difetti vanno messi a verbale?",
      a: "Tutte le difformità visibili rispetto al piano, al capitolato o alle regole tecniche. Per ogni difetto: descrizione, luogo, foto, impresa responsabile e termine. I difetti occulti vengono segnalati al momento della scoperta." },
    { cat: "docs", q: "Come conteggiare suppletivi e prestazioni aggiuntive?",
      a: "Da concordare per iscritto con il committente prima dell'esecuzione (offerta suppletiva). Quantità secondo posizioni CPN o in economia (con rapporto). Senza suppletivo approvato la remunerazione è a rischio: <strong>prima approvare, poi eseguire</strong>." },
    { cat: "docs", q: "Quali documenti archiviare a progetto concluso?",
      a: "Contratto, piani (as-built), giornale, misurazioni, verbali, misure (OTDR, compattazione), foto, autorizzazioni e bolle. Conservazione almeno <strong>10 anni</strong>; per i piani di rete in modo permanente." },

    // ===== Integrazione: Manuale della costruzione di rete sotterranea (Swisscom, 2024) =====
    { cat: "safety", q: "Come realizzare un'entrata cavi a tenuta di gas e acqua negli edifici?",
      a: "Gli elementi di tenuta devono resistere a una pressione interna o esterna di <strong>0.5 bar</strong>. Nella muratura vengono annegati tubi in acciaio; in essi si introducono i tubi plastici, sigillati con guaina termorestringente. Nei locali cavi tutte le passate vanno sigillate passivamente; per i tubi pieni si realizza un compartimento antincendio con cuscini di tenuta." },
    { cat: "safety", q: "Come proteggere i chiusini tondi dall'apertura non autorizzata?",
      a: "Con una <strong>piastra di blocco</strong> per pozzetti ø 600 mm e un <strong>lucchetto SEA</strong>. Su coperchi in ghisa e telai recenti i fori sono già presenti; sui telai più vecchi vanno praticati. Sui coperchi ghisa-cemento i fori si praticano nel collo del pozzetto." },
    { cat: "safety", q: "Si posano collegamenti equipotenziali nella costruzione del tracciato?",
      a: "In linea di principio <strong>no</strong>. Sono determinanti le direttive Swisscom per le messe a terra delle impianti cavi, le prescrizioni per la rete in rame e le indicazioni Electrosuisse per la corrente debole. Le messe a terra sono organizzate separatamente secondo queste direttive." },
    { cat: "tech", q: "Quali tipi di pozzetto utilizza Swisscom?",
      a: "Quattro tipi principali: <strong>ES</strong> (pozzetto d'ingresso, 3.00×1.50 m, per giunzioni sotto strada), <strong>KES</strong> (piccolo pozzetto d'ingresso, da 1.00×1.00 m, standard di nuova costruzione), <strong>PS</strong> (pozzetto a piastre, soprattutto in zona agricola) e <strong>KS</strong> (pozzetto di controllo, anello ø 60/80 cm). Il KES è oggi il tipo preferito; l'ES è riservato ai casi in cui lo spazio per manicotti e cavi lo richiede." },
    { cat: "tech", q: "Quando si usa un ES invece di un KES?",
      a: "L'ES è ormai un'<strong>eccezione</strong>, solo quando lo spazio per manicotti e cavi supera le capacità di un KES. In nuova costruzione si predilige il più piccolo. I pozzetti a piastre esistenti sotto pavimentazione vengono di regola convertiti in KES in fase di rinnovo." },
    { cat: "tech", q: "Dove si usano ancora i pozzetti a piastre (PS)?",
      a: "In <strong>zona agricola</strong> e su strade poco trafficate il pozzetto a piastre resta la soluzione più economica. Dimensioni standard: 1.00×1.00 m o 2.05×1.00 m con piastre in cemento 120×27 cm. In zona edificata, i PS sono ingranditi a KES in caso di rinnovo." },
    { cat: "tech", q: "Quali distanze economiche tra pozzetti nella rete di allacciamento?",
      a: "Valori di riferimento del manuale Swisscom: <strong>cavo rame d'utente</strong> ca. 200-250 m in zona edificabile, ca. 500 m fuori zona; <strong>fibra ottica</strong> ca. 1'000 m in zona edificabile, 1'000-6'000 m fuori zona. Allacciamento di dettaglio pozzetto - punto di transizione fino a ca. 200 m. Raggi minimi: K100 ≥ 3 m, K55 ≥ 1 m." },
    { cat: "tech", q: "Differenza tra allacciamento di base e di dettaglio?",
      a: "<strong>Allacciamento di base</strong>: tubi tra pozzetti visitabili (ES, KES, PS) e verso centrali e ripartitori. <strong>Allacciamento di dettaglio</strong>: tubi tra pozzetti visitabili e punti di transizione (allacciamenti clienti). Entrambi vengono dimensionati separatamente." },
    { cat: "tech", q: "Da quali strati è composta una pavimentazione stradale normata?",
      a: "Dall'alto al basso: <strong>sovrastruttura (B)</strong> con strato di usura (B4), strato di collegamento (B3), strato di base (B2), strato di fondazione (B1) e strato di transizione (B0/geotessile); <strong>infrastruttura (A)</strong> con suolo migliorato (A3), rilevato (A2) e terreno naturale (A1). Determinanti le norme VSS." },
    { cat: "tech", q: "Quale sistema di drenaggio è ammesso per i pozzetti di giunzione?",
      a: "Due possibilità secondo i piani normalizzati Swisscom: <strong>pozzo di pompaggio</strong> o <strong>pozzo perdente</strong>. Linee di drenaggio e ventilazioni non si posano di norma. Con chiusini a tenuta serrata (Gatic, Ermatic) seguire le istruzioni del produttore." },
    { cat: "tech", q: "Come controllare la compattazione attorno ai pozzetti con basamento in cemento?",
      a: "Con una <strong>prova di carico su piastra (misura ME)</strong> secondo SN 670317b o VSS-70317: carico e scarico progressivo di una piastra rigida ø 30 cm e misura del cedimento. Se i valori ME non sono raggiunti, i costi sono a carico dell'impresa esecutrice. Una compattazione insufficiente provoca un punzonamento visibile della corona in cemento." },
    { cat: "docs", q: "Quali norme sono determinanti per la costruzione sotterranea?",
      a: "<strong>SIA 205</strong> (posa di condotte sotterranee), <strong>SIA 118</strong> (condizioni generali per i lavori di costruzione), <strong>SIA 405</strong> (geodati delle reti), le <strong>norme VSS</strong> per strade e genio civile e le <strong>prescrizioni AES</strong> per gli impianti elettrici. Si aggiunge l'art. 62 dell'ordinanza sulle linee per la documentazione della posizione." },
    { cat: "docs", q: "Quali oggetti vanno rilevati per PTA?",
      a: "Tutti gli oggetti con attributo di posizione nella documentazione della rete: <strong>archi di rete</strong> (tratti interrati = linea), <strong>nodi di rete</strong> (pozzetti, derivazioni = punto) e <strong>opere speciali</strong> (ad es. grandi pozzetti = poligono). Inoltre la lunghezza del tracciato tra i nodi. PTA = Planning and Design Tool Access." },
    { cat: "docs", q: "Quale precisione è richiesta nel rilievo?",
      a: "Secondo l'<strong>art. 62 dell'ordinanza sulle linee</strong> è richiesta una precisione di posizione di <strong>±20 cm</strong>. Tale precisione si raggiunge di norma solo con rilievo a scavo aperto. La tecnologia impiegata (GNSS, tacheometro) deve essere documentata in modo tracciabile per Swisscom." },
    { cat: "docs", q: "In quale formato si consegna il rilievo digitale a Swisscom?",
      a: "Formato <strong>1× DXF</strong> con struttura <strong>SIA Geo405</strong>. Acquisizione di norma in campo con GNSS o tacheometro. Archi e nodi devono essere topologicamente coerenti – archi verso lo stesso nodo si incontrano in un punto comune." },
    { cat: "docs", q: "Cos'è il metodo dell'intersezione (Bogenschnitt)?",
      a: "Un metodo geodetico di determinazione di punto: si misurano le distanze del punto da rilevare verso <strong>due punti di coordinate note</strong> A e B. Il nuovo punto è l'intersezione dei due cerchi di centri A e B e raggi pari alle distanze misurate. Le due distanze vanno scelte il più possibile ortogonali e riportate sul piano di rilievo." },
    { cat: "docs", q: "Come funziona il rilievo ortogonale (a squadra)?",
      a: "Con un <strong>prisma a squadra</strong>, il punto da rilevare viene proiettato ad angolo retto su una linea esistente (ordinata) e si misura la distanza. Il metodo è semplice; viene riportato sul piano di rilievo." },
    { cat: "docs", q: "Come si ripartiscono i costi nei risanamenti stradali e di reti?",
      a: "Tre casi standard: <strong>nuova costruzione stradale</strong> – l'esercente partecipa per il proprio tracciato; <strong>risanamento strada o pavimentazione</strong> – contributo di norma proporzionale alla superficie utilizzata; <strong>risanamento di rete</strong> in concomitanza – contributi per coutilizzo da concordare. In caso di intralci da linee Swisscom esistenti, l'onere è oggetto di accordo separato." }
  ]
};
